openapi: 3.0.1
info:
  title: Todo Items
  description: The API for managing TODO application
  contact:
    email: mekhalajoshi2@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
tags:
- name: Todo
  description: Todo list app
paths:
  /todo:
    get:
      tags:
      - Todo
      summary: Get list of Todo items
      description: Returns list of Todo items
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Todo item not found
          content: {}
        500:
          description: Internal server error
          content: {}
    post:
      tags:
      - Todo
      summary: Create todo
      description: Creates a new todo item
      requestBody:
        description: ID of todo item to return
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Todo'
        required: true
      responses:
        201:
          description: successful operation
          content: {}
        500:
          description: Internal server error
          content: {}
      x-codegen-request-body-name: todoId
  /todo/{todoId}:
    get:
      tags:
      - Todo
      summary: Find todo by ID
      description: Returns the specific todo item
      parameters:
      - name: todoId
        in: path
        description: ID of todo item to return
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Todo item not found
          content: {}
        500:
          description: Internal server error
          content: {}
    patch:
      tags:
      - Todo
      summary: Update todo by ID
      description: Updates the specific todo item
      parameters:
      - name: todoId
        in: path
        description: ID of todo item to update
        required: true
        schema:
          type: string
      requestBody:
        description: Information of todo item to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
        required: true
      responses:
        204:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: Todo item not found
        500:
          description: Internal server error
    delete:
      tags:
      - Todo
      summary: Delete todo by ID
      description: Deletes the specific todo item
      parameters:
      - name: todoId
        in: path
        description: ID of todo item to delete
        required: true
        schema:
          type: string
      responses:
        204:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: Todo item not found
        500:
          description: Internal server error
components:
  schemas:
    Todo:
      type: object
      properties:
        todoId:
          type: integer
          format: int64
        todoText:
          type: string
        todoStatus:
          type: string
          description: Todo Status
          default: checked
          enum:
          - checked
          - unchecked
    TodoList:
      type: object
      properties:
        listItems:
          type: array
          description: The list of todo items
          items:
            $ref: '#/components/schemas/Todo'
